# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoortner', '0002_delete_kssirurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='KssirURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=220)),
                ('shortcode', models.URLField(blank=True, max_length=15, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
