# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoortner', '0003_kssirurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='kssirurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
